const NpmLifecycleStages: string[] = [
    "install",
    "pack",
    "postinstall",
    "postpack",
    "postpublish",
    "postrestart",
    "postshrinkwrap",
    "poststart",
    "poststop",
    "posttest",
    "postuninstall",
    "postversion",
    "preinstall",
    "prepack",
    "prepare",
    "prepublish",
    "prepublishOnly",
    "prerestart",
    "preshrinkwrap",
    "prestart",
    "prestop",
    "pretest",
    "preuninstall",
    "preversion",
    "publish",
    "restart",
    "shrinkwrap",
    "start",
    "stop",
    "test",
    "uninstall",
    "version",
];

enum ENpmLifecycleStages {
        install = "install",
    pack = "pack",
    postinstall = "postinstall",
    postpack = "postpack",
    postpublish = "postpublish",
    postrestart = "postrestart",
    postshrinkwrap = "postshrinkwrap",
    poststart = "poststart",
    poststop = "poststop",
    posttest = "posttest",
    postuninstall = "postuninstall",
    postversion = "postversion",
    preinstall = "preinstall",
    prepack = "prepack",
    prepare = "prepare",
    prepublish = "prepublish",
    prepublishOnly = "prepublishOnly",
    prerestart = "prerestart",
    preshrinkwrap = "preshrinkwrap",
    prestart = "prestart",
    prestop = "prestop",
    pretest = "pretest",
    preuninstall = "preuninstall",
    preversion = "preversion",
    publish = "publish",
    restart = "restart",
    shrinkwrap = "shrinkwrap",
    start = "start",
    stop = "stop",
    test = "test",
    uninstall = "uninstall",
    version = "version",
}

export {
    ENpmLifecycleStages,
    NpmLifecycleStages,
};
